name: Cross Release binary

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: rq
            name: rq-FreeBSD-x86_64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: rq.exe
            name: rq-Windows-x86_64.zip
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: rq
            name: rq-Darwin-x86_64.tar.gz
            command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{matrix.platform.os}}
          path: target/**/release/rq
      - name: Rename binaries
        run: |
          mv target/**/release/rq rq-${{matrix.platform.os}}
      - name: Generate release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release_${{ github.run_number }}
          files: |
            ./rq-${{matrix.platform.os}}
